/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifnmg.projetoPOO.gui;

import br.edu.ifnmg.projetoPOO.Usuario;

/**
 *
 * @author Filip
 */
public class JanelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form JanelaPrincipal
     */
    private Usuario usuarioSistema;

    /**
     * Creates new form Principal
     */
    public JanelaPrincipal(Usuario usuarioSistema) {
        this.usuarioSistema = usuarioSistema;
        initComponents();

        // Configuração da janela diante do perfil de administrador
        mnuAdministrador.setEnabled(usuarioSistema.isAdmin());
        mnuUsuario.setEnabled(usuarioSistema.isAdmin());
        mnuRemoverUsuario.setEnabled(usuarioSistema.isAdmin());

        // Centralização da janela
        setLocationRelativeTo(null);
    }

    public JanelaPrincipal() {
        initComponents();
        // Centralização da janela
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        dskPrincipal = new javax.swing.JDesktopPane();
        mnuBarra = new javax.swing.JMenuBar();
        mnuArquivo = new javax.swing.JMenu();
        mnuCadastro = new javax.swing.JMenu();
        mnuCadastroCliente = new javax.swing.JMenuItem();
        mnuUsuario = new javax.swing.JMenuItem();
        mnuCadastroVeiculo = new javax.swing.JMenuItem();
        mnuRemover = new javax.swing.JMenu();
        mnuRemoverCliente = new javax.swing.JMenuItem();
        mnuRemoverUsuario = new javax.swing.JMenuItem();
        mnuAdministrador = new javax.swing.JMenuItem();
        btnVaga = new javax.swing.JMenuItem();
        mnuLiberarVaga = new javax.swing.JMenuItem();
        mnuSair = new javax.swing.JMenuItem();
        mnuAjuda = new javax.swing.JMenu();
        mnuSobre = new javax.swing.JMenuItem();

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout dskPrincipalLayout = new javax.swing.GroupLayout(dskPrincipal);
        dskPrincipal.setLayout(dskPrincipalLayout);
        dskPrincipalLayout.setHorizontalGroup(
            dskPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 890, Short.MAX_VALUE)
        );
        dskPrincipalLayout.setVerticalGroup(
            dskPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 499, Short.MAX_VALUE)
        );

        mnuArquivo.setText("Arquivo");

        mnuCadastro.setText("Cadastrar");

        mnuCadastroCliente.setText("Cliente");
        mnuCadastroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCadastroClienteActionPerformed(evt);
            }
        });
        mnuCadastro.add(mnuCadastroCliente);

        mnuUsuario.setText("Usuário");
        mnuUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuUsuarioActionPerformed(evt);
            }
        });
        mnuCadastro.add(mnuUsuario);

        mnuCadastroVeiculo.setText("Veículo");
        mnuCadastroVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCadastroVeiculoActionPerformed(evt);
            }
        });
        mnuCadastro.add(mnuCadastroVeiculo);

        mnuArquivo.add(mnuCadastro);

        mnuRemover.setText("Remover");

        mnuRemoverCliente.setText("Cliente");
        mnuRemoverCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuRemoverClienteActionPerformed(evt);
            }
        });
        mnuRemover.add(mnuRemoverCliente);

        mnuRemoverUsuario.setText("Usuario");
        mnuRemoverUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuRemoverUsuarioActionPerformed(evt);
            }
        });
        mnuRemover.add(mnuRemoverUsuario);

        mnuArquivo.add(mnuRemover);

        mnuAdministrador.setText("Administrador");
        mnuArquivo.add(mnuAdministrador);

        btnVaga.setText("Ocupar Vaga");
        btnVaga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVagaActionPerformed(evt);
            }
        });
        mnuArquivo.add(btnVaga);

        mnuLiberarVaga.setText("Liberar Vaga");
        mnuLiberarVaga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuLiberarVagaActionPerformed(evt);
            }
        });
        mnuArquivo.add(mnuLiberarVaga);

        mnuSair.setText("Sair");
        mnuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSairActionPerformed(evt);
            }
        });
        mnuArquivo.add(mnuSair);

        mnuBarra.add(mnuArquivo);

        mnuAjuda.setText("Ajuda");

        mnuSobre.setText("Sobre");
        mnuSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSobreActionPerformed(evt);
            }
        });
        mnuAjuda.add(mnuSobre);

        mnuBarra.add(mnuAjuda);

        setJMenuBar(mnuBarra);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dskPrincipal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dskPrincipal)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuUsuarioActionPerformed
        CadastroUsuario cadastroUsuario = new CadastroUsuario();
        cadastroUsuario.setVisible(true);
        dskPrincipal.add(cadastroUsuario);
    }//GEN-LAST:event_mnuUsuarioActionPerformed

    private void mnuSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSobreActionPerformed
        Sobre janelaSobre = new Sobre();
        janelaSobre.setVisible(true);
        dskPrincipal.add(janelaSobre);
    }//GEN-LAST:event_mnuSobreActionPerformed

    private void btnVagaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVagaActionPerformed
        CadastroVaga cadVaga = new CadastroVaga();
        cadVaga.setVisible(true);
        dskPrincipal.add(cadVaga);
    }//GEN-LAST:event_btnVagaActionPerformed

    private void mnuCadastroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCadastroClienteActionPerformed
        CadastroCliente cadCliente = new CadastroCliente();
        cadCliente.setVisible(true);
        dskPrincipal.add(cadCliente);
    }//GEN-LAST:event_mnuCadastroClienteActionPerformed

    private void mnuRemoverClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuRemoverClienteActionPerformed
        RemoveCliente removeCliente = new RemoveCliente();
        removeCliente.setVisible(true);
        dskPrincipal.add(removeCliente);
    }//GEN-LAST:event_mnuRemoverClienteActionPerformed

    private void mnuLiberarVagaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuLiberarVagaActionPerformed
        RemoveVaga rmvVaga = new RemoveVaga();
        rmvVaga.setVisible(true);
        dskPrincipal.add(rmvVaga);

    }//GEN-LAST:event_mnuLiberarVagaActionPerformed

    private void mnuRemoverUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuRemoverUsuarioActionPerformed
        RemoveUsuario rmvUsuario = new RemoveUsuario();
        rmvUsuario.setVisible(true);
        dskPrincipal.add(rmvUsuario);

    }//GEN-LAST:event_mnuRemoverUsuarioActionPerformed

    private void mnuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSairActionPerformed
        Login telaLogin = new Login();
        telaLogin.setVisible(true);
        dispose();
    }//GEN-LAST:event_mnuSairActionPerformed

    private void mnuCadastroVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCadastroVeiculoActionPerformed
        CadastroVeiculo cadastroVeiculo = new CadastroVeiculo();
        cadastroVeiculo.setVisible(true);
        dskPrincipal.add(cadastroVeiculo);

    }//GEN-LAST:event_mnuCadastroVeiculoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btnVaga;
    private javax.swing.JDesktopPane dskPrincipal;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem mnuAdministrador;
    private javax.swing.JMenu mnuAjuda;
    private javax.swing.JMenu mnuArquivo;
    private javax.swing.JMenuBar mnuBarra;
    private javax.swing.JMenu mnuCadastro;
    private javax.swing.JMenuItem mnuCadastroCliente;
    private javax.swing.JMenuItem mnuCadastroVeiculo;
    private javax.swing.JMenuItem mnuLiberarVaga;
    private javax.swing.JMenu mnuRemover;
    private javax.swing.JMenuItem mnuRemoverCliente;
    private javax.swing.JMenuItem mnuRemoverUsuario;
    private javax.swing.JMenuItem mnuSair;
    private javax.swing.JMenuItem mnuSobre;
    private javax.swing.JMenuItem mnuUsuario;
    // End of variables declaration//GEN-END:variables
}
